exporters:
  debug:
    verbosity: detailed 
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
processors: {}
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
extensions:
  health_check: {}
  memory_ballast: {}
  zpages: {}
service:
  telemetry:
    logs:
      level: debug
  extensions:
    - health_check
    - memory_ballast
    - zpages
  pipelines:
    traces:
      exporters:
        - debug
        - otlp/jaeger
      receivers:
        - otlp

